spring:
  application:
    name: LMS.APIGateway
  cloud:
    gateway:
      routes:
      - id: LMS.Security
        uri: http://localhost:8082/
        predicates:
        - Path=/token/**
      - id: LMS.Communication
        uri: http://localhost:8089/
        predicates:
        - Path=/send/**
      - id: LMS.DiscussionForum
        uri: http://localhost:8083/
        predicates:
        - Path=/post/**
      - id: LMS.Assignment
        uri: http://localhost:8084/
        predicates:
        - Path=/assignment/**
      - id: LMS.Announcement
        uri: http://localhost:8085/
        predicates:
        - Path=/announcement/**
      - id: LMS.Quiz
        uri: http://localhost:8012/
        predicates:
        - Path=/quiz/**
      - id: LMS.TicketingSystem
        uri: http://localhost:8087/
        predicates:
        - Path=/ticket/**
      - id: LMS.Exam
        uri: http://localhost:8088/
        predicates:
        - Path=/exam/**
      - id: LMS.Calender
        uri: http://localhost:8099/
        predicates:
        - Path=/calender/**
      - id: LMS. LMS.CheckoutService
        uri: http://localhost:8092/
        predicates:
        - Path=/payment/**
      - id: LMS.BecameAnInstructor
        uri: http://localhost:8098/
        predicates:
        - Path=/instructor/**
      - id: LMS.InstituteSetup
        uri: http://localhost:8090/
        predicates:
        - Path=/api/**
      - id: LMS.Library
        uri: http://localhost:8091/
        predicates:
        - Path=/library/**
      - id: LMS.MyQuestion
        uri: http://localhost:8010/
        predicates:
        - Path=/question/**
      - id: LMS.Pricing
        uri: http://localhost:8097/
        predicates:
        - Path=/plan/**
      - id: LMS.ScoreCard
        uri: http://localhost:8095/
        predicates:
        - Path=/score/**
      - id: LMS.VideoPlayer
        uri: http://localhost:8070/
        predicates:
        - Path=/video/**
      - id: LMS.WishListservice
        uri: http://localhost:8094/
        predicates:
        - Path=/wish/**
      - id: LMS.ReviewsAndRating
        uri: http://localhost:8096/
        predicates:
        - Path=/reviews/**
      - id: LMS.ExternalService
        uri: http://localhost:8011/
        predicates:
        - Path=/external/**
      - id: LMS.Cartservice
        uri: http://localhost:8093/
        predicates:
        - Path=/cart/**
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
server:
    port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
